---
 
- name: First playbook
  hosts: my_group
  gather_facts : true 
  become: true 
  become_method: ansible.builtin.sudo
  tasks:
   - name: Print some host info 
     ansible.builtin.debug:
       msg: "THE HOST NAME IS {{ ansible_nodename }} and it is running {{ ansible_distribution }} {{ansible_distribution_version }} "
   - name: Update the packeges to the latest version
     ansible.builtin.apt:
       name : "*"
       state: "latest"
       update_cache: true     
